// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Vjwz454TzoKS02R9hVJnMLq_4dPky2o',
    appId: '1:893571555371:web:bb386e3fe02e74dcbc0a6e',
    messagingSenderId: '893571555371',
    projectId: 'auth-c3c6e',
    authDomain: 'auth-c3c6e.firebaseapp.com',
    storageBucket: 'auth-c3c6e.appspot.com',
    measurementId: 'G-TPQYME5E8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAphpbmqwduNFflVsSvkqPUu5eG4oO6N1Q',
    appId: '1:893571555371:android:1a35e922c5a98eddbc0a6e',
    messagingSenderId: '893571555371',
    projectId: 'auth-c3c6e',
    storageBucket: 'auth-c3c6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmT9OD6XJyYapdERlTLMckJB_mbwcC13o',
    appId: '1:893571555371:ios:1d02c4054823ca77bc0a6e',
    messagingSenderId: '893571555371',
    projectId: 'auth-c3c6e',
    storageBucket: 'auth-c3c6e.appspot.com',
    iosClientId: '893571555371-hir802869uul5dp4dg446313fgqt1s29.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmT9OD6XJyYapdERlTLMckJB_mbwcC13o',
    appId: '1:893571555371:ios:1d02c4054823ca77bc0a6e',
    messagingSenderId: '893571555371',
    projectId: 'auth-c3c6e',
    storageBucket: 'auth-c3c6e.appspot.com',
    iosClientId: '893571555371-hir802869uul5dp4dg446313fgqt1s29.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterauth',
  );
}
